### ISSUE TITLE
docker-compose buildが失敗する

### ISSUE THREAD

**Issue by akira345** [winebarrel/sisito#5]
Dockerで動かそうと、docker-compose buildすると、以下のようにGemfile.lockがないとエラーになります。

Step 14/26 : COPY Gemfile /tmp/sisito
 ---> Using cache
 ---> 3b2d17aa6a20
Step 15/26 : COPY Gemfile.lock /tmp/sisito
ERROR: Service 'sisito' failed to build: lstat Gemfile.lock: no such file or directory

**Comment by winebarrel** [comment]
修正しましたがどうでしょうか？

**Comment by akira345** [comment]
ありがとうございます。
無事ビルドできました。
